# Generated by Django 4.2.2 on 2023-08-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='dob',
        ),
    ]
